### ISSUE TITLE
Creating diffusers compatible model files 

### ISSUE THREAD

**Issue by benihime91** [TonyLianLong/LLM-groundedDiffusion#11]
Hi, amazing work. Just a simple question. I saw that here: https://huggingface.co/longlian/lmd_plus/ the models (SD 1.4) are already converted to use diffusers LMD+ pipeline, how can i convert my custom SD checkpoint to be compatible?

**Comment by TonyLianLong** [comment]
Since GLIGEN involves just adding adapters, it involves manually checking and matching the keys in state_dict for the adapters and converting from fp32 to fp16.

**Comment by benihime91** [comment]
do you have a script for this ? Another question what is the difference between https://huggingface.co/gligen/diffusers-inpainting-text-box & https://huggingface.co/longlian/lmd_plus, is it the same model ?

**Comment by TonyLianLong** [comment]
1. No, it's mostly manually loading the binary files with `torch.load` and then checking the keys. However, it's not that complicated because there is a pattern for adaptation. I started adaptation from SDv1.4 and added the GLIGEN adapters in a way that matches with the pipeline (not from stable diffusion's pytorch lightning repo). If you want to adapt your SD checkpoints trained with SD repo, probably there is a tool from diffusers, but that is not what I'm using for this.
2. The weights themselves are the same (since both are SD v1.4 + GLIGEN adapters) but the way that it's ordered is different I believe. The former one is for their own pipeline. The latter one is for `LLMGroundedDiffusion` pipeline, which performs the guidance in our work. You can compare the diff between the two models and the metadata of the two models.

**Comment by benihime91** [comment]
Hey thanks a lot the pointers
